### ISSUE TITLE
[accessibility] Update sample markup (headings, roles)

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-footer#126]
This report is a request for enhancement of the default markup of the o-footer.

## What

We have noticed that there are potential accessibility issues with the sample footer markup, which can be (in our opinion) easily improved.

## Details

1. The `footer` tag placed on the page root level (most common use-case) already is a landmark. It should not have another element with `role="contentinfo"` present.

2. `h6` is used in many places in the footer. In our opinion, a more suitable setup would be an `h2` (visually hidden) that describes the footer, plus `h3` for any lower level headings (similar to the setup present on ft.com)

## Additional information

While the above is not difficult to resolve during implementation, we thought it was prudent to report them.

**Comment by notlee** [comment]
I agree with both points, thank you for reporting :D 

Here's what [WAI-ARIA 1.1 says about contentinfo](https://www.w3.org/TR/wai-aria-1.1/#contentinfo):
>Within any document or application, the author SHOULD mark no more than one element with the contentinfo role.

**Comment by notlee** [comment]
this was done but I forgot to close the issue -- thanks again for reporting :)
