### ISSUE TITLE
Is this the correct way to load the Pearson sprite from the build service?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-footer#27]
We were having problems with the Pearson footer logos not appearing when it's deployed, because it's trying to load it out of the bower_components folder, which we don't deploy.

After a bit of digging around in o-assets, I found this seems to work:

```scss
$o-assets-global-path: '//build.origami.ft.com/files/';
```

But this particular setting is not in the readme of either o-footer or o-assets. Is it the right thing to do? It works, but I'm concerned there is no version tag in the URL.

**Comment by AlbertoElias** [comment]
That variable is mentioned in the o-assets readme. Maybe trying to understand how we handle assets isn't very easy and and we would love to hear feedback to improve its readme.

It is the correct way of using it and it should probably be mentioned in the footer readme as well

**Comment by callumlocke** [comment]
Is there a way to make it include a version tag in the URL?

The variable is mentioned in the o-assets readme, but it doesn't suggest
the value I'm using, that would be a good addition if it's the right way

**Comment by AlbertoElias** [comment]
Apart from the global path, you can also change the specific path for each module, so you could set the version there

**Comment by onishiweb** [comment]
Going to close this as it seems the issue was dealt with, and maybe not to do with this component.
