### ISSUE TITLE
Why is there a space in the middle of the copyright statement?

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-footer#28]
It was rasied as a defect by one of our testers as it seemed like an odd implementation.

**Comment by kaelig** [comment]
That would be one for @danskinner's team.

**Comment by Thurst-ft** [comment]
@kaelig, thanks for the feed back. One other point on this is the space as is applied  as ```margin-right`` `to ```o-footer__copyright  span ```. Should it not be ```o-footer_copyright someClass``` rather than using a tag as a selector?

**Comment by kaelig** [comment]
Yes this is entirely correct!

**Comment by danskinner** [comment]
Sorry, was on holiday...

Not sure why the gap's there - assume it was either put in to separate the two halves of the content, or by accident. Either way, it's not important. Happy for it to be removed.

**Comment by kaelig** [comment]
Thanks @danskinner 

@Thurst-ft would you like to open a PR with the changes (in a backwards compatible way, if possible)?
