### ISSUE TITLE
"Light color" version

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-footer#30]
Teams such as Interactive Graphics and membership prefer having a lighter-looking footer, closer to the current ft.com footer. As a result they end up either implementing their own or overriding o-footer.

Ideally they'd use the Origami footer instead, but with a different skin.

If the design team doesn't have time right now for that, I'll do it myself (inspired by colours currently used on ft.com).

**Comment by danskinner** [comment]
Sounds good. Should be pretty straightforward and always good to have options/alternatives where reasonable.
