### ISSUE TITLE
Footer not responsive on iOS 8

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-footer#51]
URL tested: https://origami-build.ft.com/v2/demos/o-footer@4.1.3/footer

![image](https://cloud.githubusercontent.com/assets/1115667/15901707/accd233a-2da4-11e6-9a4b-7bf03f16851d.png)

The issue is present on 3.2, as well as 4.X.

**Comment by alicebartlett** [comment]
@petrklus we've just released o-footer v5, I tried to replicate this issue in the new version but couldn't. Can you confirm it's still a problem for you?
