### ISSUE TITLE
Use real data from origami-navigation-service

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-footer#81]
Right now, our demo HTML links are generated from a static JSON file in the demos.
This is not ideal as these links change reasonably frequently (see https://github.com/financial-times/origami-navigation-service and https://github.com/Financial-Times/origami-navigation-data).

Since these footer links look real, people sometimes copy and paste them. We should make them use the actual data from the navigation service.

This could be a build step for that happens when the demos are built. This would mean the demos are up to date-ish depending on how often they are built. This would be better than what we currently have.

Or we could do something cleverer. @JakeChampion @rowanmanning what do you think?

**Comment by JakeChampion** [comment]
Makes sense. If we are okay with client-side js being required for the demo to work, we can make a request to the navigation service and build the template into html based on the response.

**Comment by rowanmanning** [comment]
I think this needs a broader discussion about how real the demo data for header and footer should be

**Comment by notlee** [comment]
Let's use dummy data like o-header https://github.com/Financial-Times/o-header/issues/160

**Comment by notlee** [comment]
https://github.com/Financial-Times/o-footer/pull/141
