### ISSUE TITLE
Remove or make the top margin optional.

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-footer#91]
The 40px margin on the top of footer makes it complicated to have any page items sit flush with it. An example would be when a full width sticky bottom banner might stick to the page at the point it meets the footer. Alternatively if we wanted to use background colours to highlight certain sections of a page it means there's always an additional strip of pink which is distracting and less than desirable. 

Also the 40px was aiming at bringing some consistency to the bottom of the various pages however this hasn't really worked with lots of other parts of a page also having bottom margins.  

Even if we can only make it optional it would make removing it easier.

**Comment by notlee** [comment]
Made optional in https://github.com/Financial-Times/o-footer/releases/tag/v6.0.10.
Issue open to consider making this the default on the next breaking release https://github.com/Financial-Times/o-footer/issues/93
